services:

  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - ./postgresql-data:/var/lib/postgresql/
    networks:
      - network-web-services

  fastapi-server:
    build: ./app/
    container_name: fastapi-server
    env_file:
      - .env
    volumes:
      - ./app/src:/app/src
    depends_on:
      - db
    ports:
      - "${FASTAPI_HOST_IP}:${FASTAPI_HOST_PORT}:8000"
    networks:
      - network-web-services


networks:
  network-web-services:
