services:

  fastapi-server-sqlite:
    build: ./app/
    container_name: fastapi-server-sqlite
    env_file:
      - .env
    volumes:
      - ./app/src:/app/src
      - ./app/databases:/app/databases
    ports:
      - "${FASTAPI_HOST_IP}:${FASTAPI_HOST_PORT}:8000"
    networks:
      - network-web-services


networks:
  network-web-services:
